### ISSUE TITLE
S2GPS 02 - Práctica Métricas de Calidad

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-entrevista-sistemhuerto#1]
[S2GPS 02 - Práctica Métricas de Calidad.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-entrevista-sistemhuerto/files/9678153/S2GPS.02.-.Practica.Metricas.de.Calidad.pdf)

**Comment by Ferch0419** [comment]
Buen trabajo: 20/20

**Comment by josealfredo79** [comment]
favor de realizar el calculo sobre el archivo que contiene la funciones del contrato inteligentes.

**Comment by josealfredo79** [comment]
favor de revisar bien @Ferch0419

**Comment by Yabin-2021** [comment]
aNEXO EL trabajo corregido...
[S2GPS 02 - Práctica Métricas de Calidad.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-entrevista-sistemhuerto/files/9707664/S2GPS.02.-.Practica.Metricas.de.Calidad.pdf)

**Comment by Ferch0419** [comment]
17/20
Faltó agregar las actividades de Moprosoft.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
